name: Create Git Tag

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Read VERSION file
      id: getversion
      run: echo "::set-output name=version::$(cat VERSION)"
      
    - name: Create Git Tag
      run: |
        git config user.email "your_email@example.com"
        git config user.name "Your Name"
        git tag -a v${{ steps.getversion.outputs.version }} -m "Release version ${{ steps.getversion.outputs.version }}"
        git push origin v${{ steps.getversion.outputs.version }}
