name: Create Git Tag

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Git Tag
      run: |
        git config user.email "your_email@example.com"
        git config user.name "Your Name"
        git tag -a v1.0.0 -m "Release version 1.0.0"
        git push origin v1.0.0
