# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build + Docker-Image

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
      
    - name: Get Version
      run: |
        cat VERSION > $VERSION
        echo "VERSION=$VERSION" >> $GITHUB_ENV
      
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
   
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.0.0
      with:
        tags: aviv27400/pinger-api-go:${{ env.VERSION }}, aviv27400/pinger-api-go:latest
        file: Dockerfile
        push: true
         
    - name: Upload Artifact
      uses: actions/upload-artifact@v3.1.2
      with: 
        name: pingerApi
        path: pingerApi
